import env from './ConfiguredEnvironment';
import * as fs from 'fs';
import * as path from 'path';

const workspaceDir = path.join(__dirname, '../../../');

const envFilePath = path.join(workspaceDir, '.env');

fs.writeFileSync(
  envFilePath,
  `# This file is autogenerated via 'yarn make:envfile'
# To override these values, copy this file to .env.local 
# and make your overrides there
${Object.keys(env)
  .map((key) => `NX_${key}=${env[key]}`)
  .join('\r\n')}`
);
console.info('Wrote environment variables to .env file');
